apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: kkevbuxcz-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:5c8fc4085203da0d92a0a1b836d9e716735fb50c@sha256:5c4d479811bee1cc761c5a651bcd67d97a21350f0b87dbef24773d726dc8e2a1
        name: container-image  
